###########################################################
# Makefile generated by xIDE                               
#                                                          
# Project: spp_dev_b
# Configuration: Release
# Generated: ÐÇÆÚ¶þ ÆßÔÂ 15 12:01:31 2014
#                                                          
# WARNING: Do not edit this file. Any changes will be lost 
#          when the project is rebuilt.                    
#                                                          
###########################################################

OUTPUT=spp_dev_b
OUTDIR=E:/elevator/elevator_SW2.0_HW3.1_release(20140605)/THYSSEN/SW/code/thyssen20131121(GecKo)
HARDWARE_INDEX=1
DEFS=-DDEV_CASIRA -DNO_DEBUG 

DEBUGTRANSPORT=SPITRANS=USB SPIPORT=0
EXECUTION_MODE=native
STACKSIZE=512
TRANSPORT=raw
FIRMWARE=unified
PANIC_ON_PANIC=1
FIRMWAREIMAGE=
LIBRARY_VERSION=

LIBS=-lconnection -lspp -lregion -lservice -lbdaddr -lsdp_parse -lbattery 
INPUTS=\
      spp_dev_b_leds.led\
      spp_dev_b_buttons.button\
      README.html\
      spp_dev_b.psr\
      led_timing.def\
      at_command.parse\
      sppb.h\
      app_state.h\
      at_command.h\
      battery_probe.h\
      battery_probe_private.h\
      bitmacro.h\
      command_return_code.h\
      debug.h\
      errman.h\
      hal.h\
      hal_config.h\
      hal_private.h\
      indication.h\
      messagebase.h\
      spp_dev_auth.h\
      spp_dev_b_buttons.h\
      spp_dev_b_leds.h\
      spp_dev_private.h\
      sppb.c\
      at_command.c\
      at_command_parse.c\
      battery_probe.c\
      debug.c\
      errman.c\
      hal.c\
      indication.c\
      main.c\
      spp_dev_auth.c\
      spp_dev_b_buttons.c\
      spp_dev_b_leds.c
# Project-specific options
characters=1
faultalerts=0
messages=1
pcvalue=0
primitives=0
timestamps=0

-include spp_dev_b.mak
include $(BLUELAB)/Makefile.vm
